/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class se_mossan_AndroidJNITestActivity */

#ifndef _Included_se_mossan_AndroidJNITestActivity
#define _Included_se_mossan_AndroidJNITestActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     se_mossan_AndroidJNITestActivity
 * Method:    print1
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_se_mossan_AndroidJNITestActivity_print1
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
